apiVersion: apps/v1
kind: Deployment
metadata:
 name: hello-nginx
spec:
 replicas: 3
 selector:
  matchLabels:
   app: hello-nginx
   version: v1
 template:
  metadata: 
   labels:
    app: hello-nginx
    version: v1
  spec:
   containers:
   - name: nginx
     image: nginx:1.17-alpine
     ports:
     - containerPort: 80
     volumeMounts:
     - mountPath: /etc/nginx/conf.d
       name: nginx-conf
       readOnly: true
   volumes:
   - name: nginx-conf
     configMap:
      name: nginx-conf
      items: 
       - key: nginx.conf
         path: nginx.conf